"""status int

Revision ID: 0698fa53b951
Revises: 2e6677c5d0b7
Create Date: 2022-11-07 14:01:51.971067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0698fa53b951'
down_revision = '2e6677c5d0b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'status')
    # ### end Alembic commands ###
