"""Commit 3

Revision ID: 2e6677c5d0b7
Revises: 45d668ec233a
Create Date: 2022-10-28 04:20:22.850260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6677c5d0b7'
down_revision = '45d668ec233a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
