"""Commit 2

Revision ID: 45d668ec233a
Revises: c8ccff489001
Create Date: 2022-10-28 03:54:09.501152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d668ec233a'
down_revision = 'c8ccff489001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
