"""Commit 1

Revision ID: c8ccff489001
Revises: 
Create Date: 2022-10-28 03:49:41.523932

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8ccff489001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('surname', sa.String(length=50), nullable=False),
                    sa.Column('country', sa.String(length=50), nullable=False),
                    sa.Column('date_of_birth', sa.Date(), nullable=False),
                    sa.Column('passport_number', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=250), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('flight',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.String(length=50), nullable=False),
                    sa.Column('departure_city', sa.String(length=50), nullable=False),
                    sa.Column('arrival_city', sa.String(length=50), nullable=False),
                    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('manager',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('surname', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=250), nullable=True),
                    sa.Column('role', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('booking',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('reservation_time', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('baggage_count', sa.Integer(), nullable=False),
                    sa.Column('flight_id', sa.Integer(), nullable=True),
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
                    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('baggage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('booking_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('boarding_check',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Integer(), nullable=False),
                    sa.Column('result', sa.Integer(), nullable=False),
                    sa.Column('manager_id', sa.Integer(), nullable=True),
                    sa.Column('booking_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
                    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boarding_check')
    op.drop_table('baggage')
    op.drop_table('booking')
    op.drop_table('manager')
    op.drop_table('flight')
    op.drop_table('client')
    # ### end Alembic commands ###
