"""user_role

Revision ID: e20f92587890
Revises: 0698fa53b951
Create Date: 2022-11-14 18:44:18.593545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20f92587890'
down_revision = '0698fa53b951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('role', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'role')
    # ### end Alembic commands ###
