CREATE TABLE client (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(45) NOT NULL,
  surname varchar(45) NOT NULL,
  country varchar(45) NOT NULL,
  date_of_birth date NOT NULL,
  passport_number int NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(250) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE manager (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(45) NOT NULL,
  surname varchar(45) NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(250) NOT NULL,
  role int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE flight (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  number varchar(45) NOT NULL,
  departure_city varchar(45) NOT NULL,
  arrival_city varchar(45) NOT NULL,
  departure_time timestamp NOT NULL,
  arrival_time timestamp NOT NULL,
  status int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE booking (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  reservation_time timestamp NOT NULL,
  baggage_count int NOT NULL,
  flight_id int NOT NULL,
  client_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (flight_id)
      REFERENCES flight (id),
  FOREIGN KEY (client_id)
      REFERENCES client (id)
);

CREATE TABLE boarding_check (
  id int NOT NULL,
  type int NOT NULL,
  result int NOT NULL,
  manager_id int NOT NULL,
  booking_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (manager_id)
      REFERENCES manager (id),
  FOREIGN KEY (booking_id)
      REFERENCES booking (id)
);

CREATE TABLE baggage (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  weight float NOT NULL,
  booking_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (booking_id)
      REFERENCES booking (id)
);
